-- Supabase SQL schema for IntelHub Archive System
-- Apply this in Supabase Dashboard → SQL editor (or CLI) using a service role.

-- Departments
create table if not exists public.department_list (
  id bigint generated by default as identity primary key,
  name text not null,
  description text not null,
  status smallint not null default 1,
  date_created timestamptz not null default now(),
  date_updated timestamptz
);

-- Curriculums
create table if not exists public.curriculum_list (
  id bigint generated by default as identity primary key,
  department_id bigint not null references public.department_list(id) on delete restrict,
  name text not null,
  description text not null,
  status smallint not null default 1,
  date_created timestamptz not null default now(),
  date_updated timestamptz
);

-- Students (minimal fields to map existing system)
create table if not exists public.student_list (
  id bigint generated by default as identity primary key,
  email text not null unique,
  firstname text,
  lastname text,
  curriculum_id bigint references public.curriculum_list(id) on delete set null,
  date_created timestamptz not null default now(),
  date_updated timestamptz
);

-- Archives (mirrors local MySQL table, uses URLs for banner/document)
create table if not exists public.archive_list (
  id bigint generated by default as identity primary key,
  archive_code varchar(100) not null,
  curriculum_id bigint not null references public.curriculum_list(id) on delete restrict,
  year smallint not null check (year between 1900 and 2100),
  title text not null,
  abstract text not null,
  members text not null,
  banner_url text not null,
  document_url text not null,
  status smallint not null default 0,
  student_id bigint references public.student_list(id) on delete set null,
  date_created timestamptz not null default now(),
  date_updated timestamptz
);

-- Helpful indexes
create index if not exists idx_archive_code on public.archive_list(archive_code);
create index if not exists idx_archive_status on public.archive_list(status);
create index if not exists idx_archive_curriculum on public.archive_list(curriculum_id);

-- Example RLS (optional): enable for archive_list when ready
-- alter table public.archive_list enable row level security;
-- create policy "public_read_published" on public.archive_list
--   for select using (status = 1);